- name: create user
  tags: always
  ansible.builtin.user:
    name: eric
    groups: root

- name: add sudoers file for eric
  tags: always
  ansible.builtin.copy:
    src: sudoers_eric
    dest: /etc/sudoers.d/eric
    owner: root
    group: root
    mode: 0440

- name: add ssh key for eric user
  tags: always
  ansible.builtin.authorized_key:
    user: eric
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILqAOwgWZ1pix1hMaCozd7MrZwB8yShopbfs20PY+TPK ed@ubuntu-wks"
